name: Deploy on Google Cloud Platform

on:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # - name: Run Lint
      #   uses: golangci/golangci-lint-action@v3

  deploy:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Authenticate Docker
        run: |
          gcloud auth configure-docker --quiet pkg.dev

      - name: Deploy to Cloud Run
        run: |
          # docker buildx build -t play .
          # gcloud config set run/region ${{ secrets.REGION }}
          # gcloud config set builds/use_kaniko True
          # gcloud config set app/cloud_build_timeout 900
          # gcloud run deploy ${{ secrets.SERVICE_NAME }} --source $(pwd) --platform managed --allow-unauthenticated
          # gcloud run services update-traffic ${{ secrets.SERVICE_NAME }} --to-latest

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.REGISTRY }}/${{ secrets.SERVICE_NAME }}:latest
          cache-from: type=registry,ref=${{ secrets.REGISTRY }}/${{ secrets.SERVICE_NAME }}:buildcache
          cache-to: type=registry,ref=${{ secrets.REGISTRY }}/${{ secrets.SERVICE_NAME }}:buildcache,mode=max
